# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wso2esb-deployment
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      # amount of pods more than the desired number of Pods during the update process
      maxSurge: 1
      # amount of pods that can be unavailable during the update process
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: wso2esb
    spec:
      containers:
      - name: wso2esb
        image: docker.wso2.com/wso2esb:4.9.0.1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nc -z localhost 8243
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - nc -z localhost 9443
          initialDelaySeconds: 30
          periodSeconds: 5
        lifecycle:
          preStop:
            exec:
              command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/wso2server.sh stop']
        imagePullPolicy: Always
        securityContext:
          runAsUser: 802
        ports:
        - containerPort: 8280
          protocol: TCP
        - containerPort: 8243
          protocol: TCP
        - containerPort: 9443
          protocol: TCP
        - containerPort: 10398
          protocol: TCP
        - containerPort: 8000
          protocol: TCP
        - containerPort: 11111
          protocol: TCP
        - containerPort: 9999
          protocol: TCP
        - containerPort: 45564
          protocol: TCP
        - containerPort: 4000
          protocol: TCP
        volumeMounts:
          # config-map-mounts
        - name: esb-conf
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf
        - name: esb-conf-axis2
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/axis2
        - name: esb-conf-datasources
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/datasources
        - name: esb-conf-tomcat
          mountPath: /home/wso2carbon/wso2-config-volume/repository/conf/tomcat
          # nfs-mounts
        - name: shared-carbonapps
          mountPath: /home/wso2carbon/wso2esb-4.9.0/repository/deployment/server/carbonapps
        - name: shared-sslprofiles
          mountPath: /home/wso2carbon/wso2esb-4.9.0/repository/conf/sslprofiles
        - name: shared-keystores
          mountPath: /home/wso2carbon/wso2esb-4.9.0/repository/resources/security
        - name: other-artifacts
          mountPath: /home/wso2carbon/wso2-artifact-volume
      volumes:
        # config-volumes
      - name: esb-conf
        configMap:
          name: esb-conf
      - name: esb-conf-axis2
        configMap:
          name: esb-conf-axis2
      - name: esb-conf-datasources
        configMap:
          name: esb-conf-datasources
      - name: esb-conf-tomcat
        configMap:
          name: esb-conf-tomcat
        # nfs-volumes
      - name: shared-carbonapps
        persistentVolumeClaim:
          claimName: shared-carbonapps-volume-claim
      - name: shared-sslprofiles
        persistentVolumeClaim:
          claimName: shared-sslprofiles-volume-claim
      - name: shared-keystores
        persistentVolumeClaim:
          claimName: shared-keystores-volume-claim
      - name: other-artifacts
        persistentVolumeClaim:
          claimName: other-artifacts-volume-claim
      serviceAccountName: "wso2svc-account"
      imagePullSecrets:
      - name: wso2creds
      hostAliases:
      - ip: 127.0.0.1
        hostnames:
        - wso2esb
        - wso2esb-gateway
